# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61398928d8e941e0ac5bc609bb454e3723c7b34d0d77c6c3853342ffa86591ae000f44d037209c28d3b9867da95056b089a6292f125673376b04036a4a57cf4c

test:
  secret_key_base: 4f7d81a19568f00c2548e3d015ab97ae1fb4a36a109f427573cd1818ffeb564713fa3d9c33b6846bd03f4a2722094036696fe7b2350ba6db0e47cb18a31bb215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
